Add backup and restore support
central-queensland-uni/moodle-local_extension pull request #93
Opened 2024-05-12 22:44 UTC by ScottVerbeek

2024-05-17 04:03 UTC, rhell4 requested changes
A few other things need cleaning up;
- [ ] Doc blocks would be nice
- [ ] Would be nice for the global $DB inclusion in `backup_local_extension_plugin.class.php` to be at the top of the function, just makes it more visible and consistent
- [ ] There's a bunch of double or triple spaces in `restore_local_extension_plugin.class.php`, these should either be single spaces or make the = lined up

2024-05-17 04:03 UTC, rhell4 commented on backup/moodle2/restore_local_extension_plugin.class.php
> +        if(!$this->task->get_setting('userinfo')) {
Missing space after if

2024-05-17 04:03 UTC, rhell4 commented on backup/moodle2/restore_local_extension_plugin.class.php
> +            $data->olditemid, $newcontext->id,
$newcontext->id should be on a new line.

2024-05-17 04:33 UTC, ScottVerbeek commented
Hi @rhell4  thanks for the review. I have amended the items listed.

2024-05-19 23:37 UTC, rhell4 approved these changes

2024-05-19 23:37 UTC, merged